/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "lib/libltc/src/ltc.h"
#include "lib/libltc/src/decoder.h"
#include "lib/libltc/src/encoder.h"


#include <stdint.h>		// Use the C99 official header


typedef ltcsnd_sample_t samplebuffer;

SWIGINTERN samplebuffer *new_samplebuffer(int nelements){
  return (ltcsnd_sample_t *) calloc(nelements,sizeof(ltcsnd_sample_t));
}
SWIGINTERN void delete_samplebuffer(samplebuffer *self){
  free(self);
}
SWIGINTERN ltcsnd_sample_t samplebuffer_getitem(samplebuffer *self,int index){
  return self[index];
}
SWIGINTERN void samplebuffer_setitem(samplebuffer *self,int index,ltcsnd_sample_t value){
  self[index] = value;
}
SWIGINTERN ltcsnd_sample_t *samplebuffer_cast(samplebuffer *self){
  return self;
}
SWIGINTERN samplebuffer *samplebuffer_frompointer(ltcsnd_sample_t *t){
  return (samplebuffer *) t;
}

typedef float floata;

SWIGINTERN floata *new_floata(int nelements){
  return (float *) calloc(nelements,sizeof(float));
}
SWIGINTERN void delete_floata(floata *self){
  free(self);
}
SWIGINTERN float floata_getitem(floata *self,int index){
  return self[index];
}
SWIGINTERN void floata_setitem(floata *self,int index,float value){
  self[index] = value;
}
SWIGINTERN float *floata_cast(floata *self){
  return self;
}
SWIGINTERN floata *floata_frompointer(float *t){
  return (floata *) t;
}

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_new_1samplebuffer(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  samplebuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (samplebuffer *)new_samplebuffer(arg1);
  *(samplebuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_delete_1samplebuffer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  samplebuffer *arg1 = (samplebuffer *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(samplebuffer **)&jarg1; 
  delete_samplebuffer(arg1);
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_samplebuffer_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jshort jresult = 0 ;
  samplebuffer *arg1 = (samplebuffer *) 0 ;
  int arg2 ;
  ltcsnd_sample_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(samplebuffer **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (ltcsnd_sample_t)samplebuffer_getitem(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_samplebuffer_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jshort jarg3) {
  samplebuffer *arg1 = (samplebuffer *) 0 ;
  int arg2 ;
  ltcsnd_sample_t arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(samplebuffer **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (ltcsnd_sample_t)jarg3; 
  samplebuffer_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_samplebuffer_1cast(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  samplebuffer *arg1 = (samplebuffer *) 0 ;
  ltcsnd_sample_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(samplebuffer **)&jarg1; 
  result = (ltcsnd_sample_t *)samplebuffer_cast(arg1);
  *(ltcsnd_sample_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_samplebuffer_1frompointer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  ltcsnd_sample_t *arg1 = (ltcsnd_sample_t *) 0 ;
  samplebuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ltcsnd_sample_t **)&jarg1; 
  result = (samplebuffer *)samplebuffer_frompointer(arg1);
  *(samplebuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_new_1floata(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  floata *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (floata *)new_floata(arg1);
  *(floata **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_delete_1floata(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  floata *arg1 = (floata *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(floata **)&jarg1; 
  delete_floata(arg1);
}


SWIGEXPORT jfloat JNICALL Java_org_gareus_libltc_LTCJNI_floata_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jfloat jresult = 0 ;
  floata *arg1 = (floata *) 0 ;
  int arg2 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(floata **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (float)floata_getitem(arg1,arg2);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_floata_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jfloat jarg3) {
  floata *arg1 = (floata *) 0 ;
  int arg2 ;
  float arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(floata **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (float)jarg3; 
  floata_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_floata_1cast(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  floata *arg1 = (floata *) 0 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(floata **)&jarg1; 
  result = (float *)floata_cast(arg1);
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_floata_1frompointer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  float *arg1 = (float *) 0 ;
  floata *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(float **)&jarg1; 
  result = (floata *)floata_frompointer(arg1);
  *(floata **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1frame_1units_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->frame_units = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1frame_1units_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->frame_units);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user1_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->user1 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user1_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->user1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1frame_1tens_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->frame_tens = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1frame_1tens_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->frame_tens);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1dfbit_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->dfbit = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1dfbit_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->dfbit);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1col_1frame_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->col_frame = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1col_1frame_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->col_frame);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user2_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->user2 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user2_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->user2);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1secs_1units_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->secs_units = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1secs_1units_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->secs_units);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user3_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->user3 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user3_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->user3);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1secs_1tens_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->secs_tens = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1secs_1tens_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->secs_tens);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1biphase_1mark_1phase_1correction_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->biphase_mark_phase_correction = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1biphase_1mark_1phase_1correction_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->biphase_mark_phase_correction);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user4_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->user4 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user4_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->user4);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1mins_1units_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->mins_units = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1mins_1units_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->mins_units);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user5_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->user5 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user5_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->user5);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1mins_1tens_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->mins_tens = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1mins_1tens_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->mins_tens);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1binary_1group_1flag_1bit0_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->binary_group_flag_bit0 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1binary_1group_1flag_1bit0_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->binary_group_flag_bit0);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user6_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->user6 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user6_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->user6);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1hours_1units_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->hours_units = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1hours_1units_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->hours_units);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user7_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->user7 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user7_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->user7);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1hours_1tens_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->hours_tens = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1hours_1tens_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->hours_tens);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1binary_1group_1flag_1bit1_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->binary_group_flag_bit1 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1binary_1group_1flag_1bit1_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->binary_group_flag_bit1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1binary_1group_1flag_1bit2_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->binary_group_flag_bit2 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1binary_1group_1flag_1bit2_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->binary_group_flag_bit2);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user8_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->user8 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1user8_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->user8);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1sync_1word_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->sync_word = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrame_1sync_1word_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrame **)&jarg1; 
  result = (unsigned int) ((arg1)->sync_word);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_new_1LTCFrame(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct LTCFrame *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct LTCFrame *)calloc(1, sizeof(struct LTCFrame));
  *(struct LTCFrame **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_delete_1LTCFrame(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct LTCFrame *arg1 = (struct LTCFrame *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct LTCFrame **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_LTC_1USE_1DATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum LTC_BG_FLAGS result;
  
  (void)jenv;
  (void)jcls;
  result = (enum LTC_BG_FLAGS)LTC_USE_DATE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_LTC_1TC_1CLOCK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum LTC_BG_FLAGS result;
  
  (void)jenv;
  (void)jcls;
  result = (enum LTC_BG_FLAGS)LTC_TC_CLOCK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_LTC_1BGF_1DONT_1TOUCH_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum LTC_BG_FLAGS result;
  
  (void)jenv;
  (void)jcls;
  result = (enum LTC_BG_FLAGS)LTC_BGF_DONT_TOUCH;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_LTC_1NO_1PARITY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum LTC_BG_FLAGS result;
  
  (void)jenv;
  (void)jcls;
  result = (enum LTC_BG_FLAGS)LTC_NO_PARITY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1ltc_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  LTCFrame arg2 ;
  LTCFrame *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  argp2 = *(LTCFrame **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null LTCFrame");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->ltc = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1ltc_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  LTCFrame result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  result =  ((arg1)->ltc);
  {
    LTCFrame * resultptr = (LTCFrame *) malloc(sizeof(LTCFrame));
    memmove(resultptr, &result, sizeof(LTCFrame));
    *(LTCFrame **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1off_1start_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  ltc_off_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  arg2 = (ltc_off_t)jarg2; 
  if (arg1) (arg1)->off_start = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1off_1start_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  ltc_off_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  result = (ltc_off_t) ((arg1)->off_start);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1off_1end_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  ltc_off_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  arg2 = (ltc_off_t)jarg2; 
  if (arg1) (arg1)->off_end = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1off_1end_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  ltc_off_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  result = (ltc_off_t) ((arg1)->off_end);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1reverse_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->reverse = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1reverse_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  result = (int) ((arg1)->reverse);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1biphase_1tics_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  floata *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  arg2 = *(floata **)&jarg2; 
  {
    size_t ii;
    floata *b = (floata *) arg1->biphase_tics;
    for (ii = 0; ii < (size_t)LTC_FRAME_BIT_COUNT; ii++) b[ii] = *((floata *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1biphase_1tics_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  floata *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  result = (floata *)(floata *) ((arg1)->biphase_tics);
  *(floata **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1sample_1min_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  ltcsnd_sample_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  arg2 = (ltcsnd_sample_t)jarg2; 
  if (arg1) (arg1)->sample_min = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1sample_1min_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  ltcsnd_sample_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  result = (ltcsnd_sample_t) ((arg1)->sample_min);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1sample_1max_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  ltcsnd_sample_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  arg2 = (ltcsnd_sample_t)jarg2; 
  if (arg1) (arg1)->sample_max = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1sample_1max_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  ltcsnd_sample_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  result = (ltcsnd_sample_t) ((arg1)->sample_max);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1volume_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->volume = arg2;
}


SWIGEXPORT jdouble JNICALL Java_org_gareus_libltc_LTCJNI_LTCFrameExt_1volume_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  result = (double) ((arg1)->volume);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_new_1LTCFrameExt(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct LTCFrameExt *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct LTCFrameExt *)calloc(1, sizeof(struct LTCFrameExt));
  *(struct LTCFrameExt **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_delete_1LTCFrameExt(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct LTCFrameExt *arg1 = (struct LTCFrameExt *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct LTCFrameExt **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1timezone_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  char *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->timezone, (const char *)arg2, 6-1);
      arg1->timezone[6-1] = 0;
    } else {
      arg1->timezone[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1timezone_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  result = (char *)(char *) ((arg1)->timezone);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1years_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  if (arg1) (arg1)->years = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1years_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  result = (unsigned char) ((arg1)->years);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1months_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  if (arg1) (arg1)->months = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1months_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  result = (unsigned char) ((arg1)->months);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1days_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  if (arg1) (arg1)->days = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1days_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  result = (unsigned char) ((arg1)->days);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1hours_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  if (arg1) (arg1)->hours = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1hours_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  result = (unsigned char) ((arg1)->hours);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1mins_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  if (arg1) (arg1)->mins = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1mins_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  result = (unsigned char) ((arg1)->mins);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1secs_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  if (arg1) (arg1)->secs = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1secs_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  result = (unsigned char) ((arg1)->secs);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1frame_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  if (arg1) (arg1)->frame = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_SMPTETimecode_1frame_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  result = (unsigned char) ((arg1)->frame);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_new_1SMPTETimecode(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct SMPTETimecode *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct SMPTETimecode *)calloc(1, sizeof(struct SMPTETimecode));
  *(struct SMPTETimecode **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_delete_1SMPTETimecode(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct SMPTETimecode *arg1 = (struct SMPTETimecode *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct SMPTETimecode **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1queue_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  LTCFrameExt *arg2 = (LTCFrameExt *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = *(LTCFrameExt **)&jarg2; 
  if (arg1) (arg1)->queue = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1queue_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  LTCFrameExt *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (LTCFrameExt *) ((arg1)->queue);
  *(LTCFrameExt **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1queue_1len_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->queue_len = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1queue_1len_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (int) ((arg1)->queue_len);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1queue_1read_1off_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->queue_read_off = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1queue_1read_1off_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (int) ((arg1)->queue_read_off);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1queue_1write_1off_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->queue_write_off = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1queue_1write_1off_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (int) ((arg1)->queue_write_off);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1biphase_1state_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  unsigned char arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  if (arg1) (arg1)->biphase_state = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1biphase_1state_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (unsigned char) ((arg1)->biphase_state);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1biphase_1prev_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  unsigned char arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  if (arg1) (arg1)->biphase_prev = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1biphase_1prev_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (unsigned char) ((arg1)->biphase_prev);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1snd_1to_1biphase_1state_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  unsigned char arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  if (arg1) (arg1)->snd_to_biphase_state = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1snd_1to_1biphase_1state_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (unsigned char) ((arg1)->snd_to_biphase_state);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1snd_1to_1biphase_1cnt_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->snd_to_biphase_cnt = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1snd_1to_1biphase_1cnt_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (int) ((arg1)->snd_to_biphase_cnt);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1snd_1to_1biphase_1lmt_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->snd_to_biphase_lmt = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1snd_1to_1biphase_1lmt_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (int) ((arg1)->snd_to_biphase_lmt);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1snd_1to_1biphase_1period_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->snd_to_biphase_period = arg2;
}


SWIGEXPORT jdouble JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1snd_1to_1biphase_1period_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (double) ((arg1)->snd_to_biphase_period);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1snd_1to_1biphase_1min_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  ltcsnd_sample_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (ltcsnd_sample_t)jarg2; 
  if (arg1) (arg1)->snd_to_biphase_min = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1snd_1to_1biphase_1min_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  ltcsnd_sample_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (ltcsnd_sample_t) ((arg1)->snd_to_biphase_min);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1snd_1to_1biphase_1max_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  ltcsnd_sample_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (ltcsnd_sample_t)jarg2; 
  if (arg1) (arg1)->snd_to_biphase_max = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1snd_1to_1biphase_1max_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  ltcsnd_sample_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (ltcsnd_sample_t) ((arg1)->snd_to_biphase_max);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1decoder_1sync_1word_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  unsigned short arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (unsigned short)jarg2; 
  if (arg1) (arg1)->decoder_sync_word = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1decoder_1sync_1word_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  unsigned short result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (unsigned short) ((arg1)->decoder_sync_word);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1ltc_1frame_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  LTCFrame arg2 ;
  LTCFrame *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  argp2 = *(LTCFrame **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null LTCFrame");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->ltc_frame = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1ltc_1frame_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  LTCFrame result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result =  ((arg1)->ltc_frame);
  {
    LTCFrame * resultptr = (LTCFrame *) malloc(sizeof(LTCFrame));
    memmove(resultptr, &result, sizeof(LTCFrame));
    *(LTCFrame **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1bit_1cnt_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->bit_cnt = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1bit_1cnt_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (int) ((arg1)->bit_cnt);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1frame_1start_1off_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  ltc_off_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (ltc_off_t)jarg2; 
  if (arg1) (arg1)->frame_start_off = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1frame_1start_1off_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  ltc_off_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (ltc_off_t) ((arg1)->frame_start_off);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1frame_1start_1prev_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  ltc_off_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (ltc_off_t)jarg2; 
  if (arg1) (arg1)->frame_start_prev = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1frame_1start_1prev_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  ltc_off_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (ltc_off_t) ((arg1)->frame_start_prev);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1biphase_1tics_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  floata *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = *(floata **)&jarg2; 
  {
    size_t ii;
    floata *b = (floata *) arg1->biphase_tics;
    for (ii = 0; ii < (size_t)LTC_FRAME_BIT_COUNT; ii++) b[ii] = *((floata *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1biphase_1tics_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  floata *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (floata *)(floata *) ((arg1)->biphase_tics);
  *(floata **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1biphase_1tic_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->biphase_tic = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_LTCDecoder_1biphase_1tic_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  result = (int) ((arg1)->biphase_tic);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_new_1LTCDecoder(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct LTCDecoder *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct LTCDecoder *)calloc(1, sizeof(struct LTCDecoder));
  *(struct LTCDecoder **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_delete_1LTCDecoder(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct LTCDecoder *arg1 = (struct LTCDecoder *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct LTCDecoder **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_ltc_1frame_1to_1time(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  SMPTETimecode *arg1 = (SMPTETimecode *) 0 ;
  LTCFrame *arg2 = (LTCFrame *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(SMPTETimecode **)&jarg1; 
  arg2 = *(LTCFrame **)&jarg2; 
  arg3 = (int)jarg3; 
  ltc_frame_to_time(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_ltc_1time_1to_1frame(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3, jint jarg4) {
  LTCFrame *arg1 = (LTCFrame *) 0 ;
  SMPTETimecode *arg2 = (SMPTETimecode *) 0 ;
  enum LTC_TV_STANDARD arg3 ;
  int arg4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(LTCFrame **)&jarg1; 
  arg2 = *(SMPTETimecode **)&jarg2; 
  arg3 = (enum LTC_TV_STANDARD)jarg3; 
  arg4 = (int)jarg4; 
  ltc_time_to_frame(arg1,arg2,arg3,arg4);
}


SWIGEXPORT jlong JNICALL Java_org_gareus_libltc_LTCJNI_ltc_1decoder_1create(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  LTCDecoder *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (LTCDecoder *)ltc_decoder_create(arg1,arg2);
  *(LTCDecoder **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_ltc_1decoder_1write(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jlong jarg3, jlong jarg4) {
  LTCDecoder *arg1 = (LTCDecoder *) 0 ;
  samplebuffer *arg2 = (samplebuffer *) 0 ;
  size_t arg3 ;
  ltc_off_t arg4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(LTCDecoder **)&jarg1; 
  arg2 = *(samplebuffer **)&jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = (ltc_off_t)jarg4; 
  ltc_decoder_write(arg1,arg2,arg3,arg4);
}


SWIGEXPORT jint JNICALL Java_org_gareus_libltc_LTCJNI_ltc_1decoder_1read(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  LTCDecoder *arg1 = (LTCDecoder *) 0 ;
  LTCFrameExt *arg2 = (LTCFrameExt *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(LTCDecoder **)&jarg1; 
  arg2 = *(LTCFrameExt **)&jarg2; 
  result = (int)ltc_decoder_read(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_decode_1ltc(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  LTCDecoder *arg1 = (LTCDecoder *) 0 ;
  ltcsnd_sample_t *arg2 = (ltcsnd_sample_t *) 0 ;
  size_t arg3 ;
  ltc_off_t arg4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LTCDecoder **)&jarg1; 
  arg2 = *(ltcsnd_sample_t **)&jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = (ltc_off_t)jarg4; 
  decode_ltc(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_org_gareus_libltc_LTCJNI_ltc_1decoder_1queue_1flush(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  LTCDecoder *arg1 = (LTCDecoder *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LTCDecoder **)&jarg1; 
  ltc_decoder_queue_flush(arg1);
}


#ifdef __cplusplus
}
#endif

